### ISSUE TITLE
Unclear output meaning

### ISSUE THREAD

**Issue by Floyddotnet** [AmesCornish/buttersink#12]
What is the different between this to lines?

```
Keep: ff80...9f8d /media/BACKUP/owncloud/daily_2015-09-29_07:41:09 from None (237.5 MiB)
Keep: 1164...42ef /media/BACKUP/owncloud/daily_2015-10-02_07:58:12 from b9b3...ab1e /media/BACKUP/owncloud/daily_2015-10-01_08:11:30 (~3.551 MiB)
```

after calling

```
buttersink -d /media/RAID/owncloud/.snapshot/ /media/BACKUP/owncloud/
```

in spezial the "from" value of the 2. line is confusing me.

**Comment by AmesCornish** [comment]
The first line in your snippet indicates a full snapshot that would be kept or transferred.  The second line indicates a diff between two snapshots would be kept or transferred -- specifically the difference from daily_2015-10-01_08:11:30 to daily_2015-10-02_07:58:12. 

When the snapshots and differences are being kept on a btrfs destination, it doesn't really matter whether buttersink is tallying diffs or full snapshots.  When it's on a source, it matters a lot because the diffs are usually much smaller.

**Comment by Floyddotnet** [comment]
But is this right that both snapshots (in line 2) are from "/media/BACKUP/"?

Should it not look more like this:

Keep: 1164...42ef /media/**BACKUP**/owncloud/daily_2015-10-02_07:58:12 from b9b3...ab1e /media/**RAID**/owncloud/daily_2015-10-01_08:11:30 (~3.551 MiB)

Keep BACKUP from RAID? and not Keep BACKUP from BACKUP?

**Comment by AmesCornish** [comment]
Yes, it's right that the diff is between two snapshots in BACKUP.  You're sink'ing from RAID to BACKUP.  Buttersink sees that it could transmit daily_2015-10-02_07:58:12 into a new destination from BACKUP, namely by transferring a diff between daily_2015-10-02_07:58:12 from daily_2015-10-01_08:11:30 to the new destination.  Since BACKUP already (implicitly) contains this diff, buttersink will just "Keep" the diff in BACKUP, and doesn't need to xfer anything from RAID.

"Keep daily_2015-10-02_07:58:12 from daily_2015-10-01_08:11:30" means to keep in the destination, the diff between daily_2015-10-01_08:11:30 and daily_2015-10-02_07:58:12.

HTH!

**Comment by Floyddotnet** [comment]
ok thanks for the clarification.
