### ISSUE TITLE
Truncate error during btrfs send

### ISSUE THREAD

**Issue by AmesCornish** [AmesCornish/buttersink#15]
This is a new issue for the problems discussed in #14 .

Youam,

You may be running into one of various btrfs tools and kernel bugs, for example:

http://forum.rockstor.com/t/apparent-issues-with-quotas-and-snapshots/252
http://www.spinics.net/lists/linux-btrfs/msg48968.html
https://www.mail-archive.com/search?l=linux-btrfs@vger.kernel.org&q=subject:%22Re%3A+btrfs+send+and+kernel+3.17%22&o=newest&f=1
https://github.com/markfasheh/duperemove/issues/50
http://www.spinics.net/lists/linux-btrfs/msg42279.html

These errors are not fully understood yet, but here are a few things to try to see if you can narrow down the problem:
- Do a rebalance: `sudo btrfs bal start <path>`
- Turn quota off: `sudo btrfs quota disable <path>`
  (of course buttersink will turn quota back on the next time it's run)
- Try a scrub: `sudo btrfs scrub start <path>`
- Try updating your kernel or btrfs tools

I'm opening a new issue for this.

**Comment by youam** [comment]
you're probably right. scrubbing the source filesystem showed uncorrectable errors, and I've run duperemove on there in the past (a while back, because duperemove doesn't really cope with my usecase of 1TB volume with daily snapshots of about 20 vms, that is, millions of files which share their extends more than 40 times, each). I figure that this really is a btrfs problem, which just wasn't visible before I tried moving snapshots to different filesystems with buttersink.
