### ISSUE TITLE
Details of "Intelligent selection of full and incremental transfers"

### ISSUE THREAD

**Issue by flungo** [AmesCornish/buttersink#22]
I can see from using that not all snapshots, are dependant on previous snapshots when uploaded to S3: scrolling down the list of files in the S3 file explorer I can see that there are breaks in the places where a `.bs` file exists. I assume that these breaks are what make the backups more resilient with occasional full backups rather than constantly depending on the last snapshot.

My reason for asking is the want to setup long term retention in glacier storage. Once moved to glacier, the files cannot be directly accessed via S3. Are there any guarantees as to when full backups will be made? Can I safely move data older than 60 days to glacier and still be able to access say the last day, week or month of backups?

I was interested in the exact system behind these decisions and hoping that there could be some documentation on this - either within the README or the wiki.

It would also be interesting/useful to know exactly how the data is structured on the S3 side. For example, would it be possible to restore from S3 without `buttersink` using `btrfs receive` and piping the files stored on S3 to it (obviously by first following the snapshot dependencies backwards and then importing in the forward order).

**Comment by AmesCornish** [comment]
You're correct that  the backups are more resilient because buttersink does occasional full backups, and tries to reduce the length of the chain of differences required to restore any particular snapshot.  

The algorithm for this is heuristic.  Buttersink uses some factors for the cost of transferring the data to S3, of storing the data in S3, and of the likelihood of failure based on the amount of data and number of files that could possible be corrupted.  It then attempts to find the "differences" that create the most resilient backups for the least cost.  Because it is a heuristic algorithm, the exact scheme differs based on the data and the current set of differences in S3.  It would be hard to predict the results in advance.

You have probably notices that the differences are labeled with a "to...from" scheme, so you can see what differences are dependent on what other differences.

Though I have not used Glacier personally, I did think about it during the design of buttersink.  My vision of how to use it would be to set up an AWS policy to rotate your S3 differences into Glacier.  As long as you leave the ".bs" alone, buttersink should be able to continue backing-up your snapshots.  When you restore, you may need to request that AWS transfer a file from glacier back to S3.

Another possibility would be to backup to two separate buckets -- one for normal S3 and another where you have Glacier configured.  Then any restores from the plain S3 bucket would never need a transfer from Glacier.

As you can see, buttersink hasn't been tested with  Glacier much, so if you  try it, I'd be interested in your experiences with either of the two methods above.

In answer to your question about `btrfs receive`, yes, the files are pure btrfs send data, and so should work normally with `btrfs receive`.  FYI, buttersink does some extra things to enable things like restoring from a combination of local snapshots and remote "send" backup data, which btrfs does not support.

Thanks!
